language: java

build: trusty

jdk:

- oraclejdk8

git:
  quiet: true

before_script:
- wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip 

addons:
apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

install: true

  chrome: stable
  apt:
    packages:
      - chromium-chromedriver
      
before_script:
  # include ChromeDriver in PATH
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  # start Chrome and listen on localhost
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
-chmod +x chromedriver

script: 
- ./mvnw clean install
- mvn clean install -U
- mvn dependency::tree
- mvn clean test
- mvn -f pom.xml test


after_failure:
- cat target/surefire-reports/*.txt
